drop table if exists actor cascade 
drop table if exists category cascade 
drop table if exists film cascade 
drop table if exists film_actor cascade 
drop table if exists film_category cascade 
drop table if exists language cascade 
create table actor (actor_id integer generated by default as identity, last_update timestamp(6), first_name varchar(45) not null, last_name varchar(45) not null, primary key (actor_id))
create table category (category_id integer generated by default as identity, last_update timestamp(6), name varchar(25) not null, primary key (category_id))
create table film (film_id integer generated by default as identity, language_id integer not null, length integer, original_language_id integer, release_year smallint check ((release_year>=1901) and (release_year<=2155)), rental_duration tinyint not null, rental_rate numeric(4,2) not null, replacement_cost numeric(5,2) not null, last_update timestamp(6), title varchar(128) not null, rating varchar(255), special_features varchar(255), description clob, primary key (film_id))
create table film_actor (actor_id integer not null, film_id integer not null, last_update timestamp(6), primary key (actor_id, film_id))
create table film_category (category_id integer not null, film_id integer not null, last_update timestamp(6), primary key (category_id, film_id))
create table language (language_id integer generated by default as identity, last_update timestamp(6), name varchar(20) not null, primary key (language_id))
alter table if exists film add constraint FK_film_language_id foreign key (language_id) references language
alter table if exists film add constraint FK_film_original_language_id foreign key (original_language_id) references language
alter table if exists film_actor add constraint FK_film_actor_actor foreign key (actor_id) references actor
alter table if exists film_actor add constraint FK_film_actor_film foreign key (film_id) references film
alter table if exists film_category add constraint FK_film_category_category foreign key (category_id) references category
alter table if exists film_category add constraint FK_film_category_film foreign key (film_id) references film