# Normal
# empaquetar: mvnw clean package
FROM eclipse-temurin:21-alpine
COPY target/ms-eureka-server-1.0.0.jar /usr/app.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/usr/app.jar"]

# crear imagen: docker build -t jamarton/ms-eureka-server:1.0.0 -t jamarton/ms-eureka-server:latest .
# crear contenedor: docker run -d --name ms-eureka-server -p 8761:8761 jamarton/ms-eureka-server
# añadir a red: docker network connect microservicios ms-eureka-server

# Nativa
# generar: mvnw clean spring-boot:build-image
#FROM ms-eureka-server-native:1.0.0
#EXPOSE 8761

# crear imagen: docker build -f dockerfile-native -t ms-eureka-server-native .
# crear contenedor: docker run -d --name ms-eureka-server-native -p 8761:8761 ms-eureka-server-native
# añadir a red: docker network connect microservicios ms-eureka-server-native
