# Normal
# empaquetar: mvnw clean package
FROM eclipse-temurin:21-alpine
COPY target/ms-authentication-1.0.0.jar /usr/app.jar
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app.jar"]

# Nativa
# generar: mvnw clean spring-boot:build-image
# FROM ms-authentication:0.0.1-SNAPSHOT
# ENV PORT=8080
# EXPOSE 8080

# crear imagen: docker build -t ms-authentication-server .
# crear contenedor: docker run -d --name ms-authentication-server -p 8091:8080 --env DISCOVERY_URL=http://ms-eureka-server:8761 --env CONFIGSRV_URL=http://ms-config-server:8888/ ms-authentication-server
# añadir a red: docker network connect microservicios ms-authentication-server
