@AuthenticationServer_HostAddress = http://localhost:5039
@usr = "emp@example.com"

###

@name = getToken

POST {{AuthenticationServer_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{ "username": {{usr}}, "password": "P@$$w0rd" }

###

GET {{AuthenticationServer_HostAddress}}/auth/auth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbXBAZXhhbXBsZS5jb20iLCJyb2xlcyI6WyJVc3VhcmlvcyIsIkVtcGxlYWRvcyJdLCJuYmYiOjE3NTE3NTMxMDQsImV4cCI6MTc1MTc1MzQwNCwiaWF0IjoxNzUxNzUzMTA0LCJpc3MiOiJNaWNyb3NlcnZpY2lvc0pXVCIsImF1ZCI6ImF1dGhvcml6YXRpb24ifQ.noKgTgL0BjzlPx7M44rbIyeay8z9Er3ZCnrEIYOlS09jhvHbDmxitOsLLJN3pF4Sp5r3TJfn3Z04ooU5Fu1Mcw1rkCr78tSy4-yIXqtHtl2VNxteu8tDinYK7tVSmH_76fojb0vekilKpD9GVyqjfpbSDMmAAXcoG7NHTjZK3yHJlBk7QqycJvDR94k-W20EQM5T80B9E-ZEPXtI2AMp-sxvNyoT-NxBNJTul0MMX2HANc26VyzV01wl6mk68tJMwpOtVpeCbQuElZDJ0aMPyPFsiEZCQlUFI8iW09nLDKBKEBlpH-PUMsHGcB1PY1VgN1SeY4TcvYv09DlQ27RryA

###

POST {{AuthenticationServer_HostAddress}}/auth/refresh
Accept: application/json
Content-Type: application/json

{ "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1AZXhhbXBsZS5jb20iLCJpYXQiOjE3NTE3NDkyMTYsIm5iZiI6MTc1MTc0OTUxNiwiZXhwIjoxNzUxNzUwNDE2LCJhdWQiOiJhdXRob3JpemF0aW9uIiwiaXNzIjoiTWljcm9zZXJ2aWNpb3NKV1QifQ.smjuA8sH3KOCOtHSjeU1krveQNL3eFLbVLHDzssyu-4" }


###

POST {{AuthenticationServer_HostAddress}}/auth/refresh
Accept: application/json
Content-Type: application/json

{ "token": {{response.body.$.refresh}} }


###

GET {{AuthenticationServer_HostAddress}}/auth/signature
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlbXBAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImVtcEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIlVzdWFyaW9zIiwiRW1wbGVhZG9zIl0sIm5iZiI6MTc1MTY1NjM2MCwiZXhwIjoxNzUxNjU2NjYwLCJpYXQiOjE3NTE2NTYzNjAsImlzcyI6Ik1pY3Jvc2VydmljaW9zSldUIiwiYXVkIjoiYXV0aG9yaXphdGlvbiJ9.K9uLJyTC1_XCy_gQvU0rpFjtTbc6pkArWswzVsN7tQp0fw7Az5bDRXhm1DUB4WxdgvJgrt7gcQtHzK0ztsWuNTtw2FZKY3AbVzJs-uhFOLLoGxXgokTahMHbtQpf5oBVzqulPEZVxlXdd2CauGekV8P_A6i0VjdzoSdH76JZGgaZPKcrkRTjUp9U4L0nOoWMXh0ElEPou4pDnn-7X1pZTX6vkhmNrWdYgwIw_r3qxO6Se6Fd-o7gs7688XAuEpuCtU3bx5ta98kdeUJYoybAT2WOqXYKVDziwhQC0jL-uptfAAB08P6Kkp8D6xC6uyFfTUvpsr8ULZHGwuO57u7qpA




###

GET http://localhost:5069/api/Categorias/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbUBleGFtcGxlLmNvbSIsInJvbGVzIjpbIlVzdWFyaW9zIiwiQWRtaW5pc3RyYWRvcmVzIl0sIm5iZiI6MTc1MDg4NjA3NywiZXhwIjoxNzUwODg2Mzc3LCJpYXQiOjE3NTA4ODYwNzcsImlzcyI6Ik1pY3Jvc2VydmljaW9zSldUIiwiYXVkIjoiYXV0aG9yaXphdGlvbiJ9.WHkZoGMrbL105rSxq7RKrRJhM2XVQWadTG5GJMV_37oHc8TigOjgl4fA66tLBS8dZ5YorAPNare9GewwYmRRKRF4TuEHzgGrmmOrviZ_pyIyHoZ6ciJiDgNahNwgwkQGmT4XjEkf2n3HLgmyKNwFtv1ntdWVPywmhVG2GTyAKyDSj4-1gauh2OgF0kx3SVhiMQmUh5ORdLZtsvSUOSZg8KO5wXVv_t0l5MtQZRD-NRASAhVq2K3psTLrxymeAE2PlFe9Ag9rGzM9odNZujsp2WwQqSqqte-ubXj417Rj7CNHmNRGh9u9wjF6vtleDmZEeT1DfKd-y95YeZ29a1gkIg
