// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using TiendaAW.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TiendaAW.Models;

public partial class ProductEdit {
    [Description("Primary key for Product records.")]
    public int ProductId { get; set; }

    [Description("Name of the product.")]
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Description("Unique product identification number.")]
    [Required]
    [StringLength(25)]
    public string ProductNumber { get; set; }

    [Description("Product color.")]
    [StringLength(15)]
    public string Color { get; set; }

    [Description("Standard cost of the product.")]
    public decimal StandardCost { get; set; }

    [Description("Selling price.")]
    public decimal ListPrice { get; set; }

    [Description("Product size.")]
    [StringLength(5)]
    public string Size { get; set; }

    [Description("Product weight.")]
    public decimal? Weight { get; set; }

    [Description("Product is a member of this product category.")]
    public int? ProductCategoryId { get; set; }

    [Description("Product is a member of this product model.")]
    public int? ProductModelId { get; set; }

    [Description("Date the product was available for sale.")]
    public DateTime SellStartDate { get; set; }

    [Description("Date the product was no longer available for sale.")]
    public DateTime? SellEndDate { get; set; }

    [Description("Date the product was discontinued.")]
    public DateTime? DiscontinuedDate { get; set; }

    public Product merge(Product item) {
        item.ProductId = ProductId;
        item.Name = Name;
        item.ProductNumber = ProductNumber;
        item.Color = Color;
        item.StandardCost = StandardCost;
        item.ListPrice = ListPrice;
        item.Size = Size;
        item.Weight = Weight;
        item.ProductCategoryId = ProductCategoryId;
        item.ProductModelId = ProductModelId;
        item.SellStartDate = SellStartDate;
        item.SellEndDate = SellEndDate;
        item.DiscontinuedDate = DiscontinuedDate;
        return item;
    }

    public static ProductEdit from(Product item) {
        return new ProductEdit {
            ProductId = item.ProductId,
            Name = item.Name,
            ProductNumber = item.ProductNumber,
            Color = item.Color,
            StandardCost = item.StandardCost,
            ListPrice = item.ListPrice,
            Size = item.Size,
            Weight = item.Weight,
            ProductCategoryId = item.ProductCategoryId,
            ProductModelId = item.ProductModelId,
            SellStartDate = item.SellStartDate,
            SellEndDate = item.SellEndDate,
            DiscontinuedDate = item.DiscontinuedDate
        };
    }

}

