// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using TiendaAW.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TiendaAW.Models;

public partial class ProductDetail {
    [Description("Primary key for Product records.")]
    public int ProductId { get; set; }

    [Description("Name of the product.")]
    public string Name { get; set; }

    [Description("Unique product identification number.")]
    public string ProductNumber { get; set; }

    [Description("Product color.")]
    public string Color { get; set; }

    [Description("Standard cost of the product.")]
    public decimal StandardCost { get; set; }

    [Description("Selling price.")]
    public decimal ListPrice { get; set; }

    [Description("Product size.")]
    public string Size { get; set; }

    [Description("Product weight.")]
    public decimal? Weight { get; set; }

    [Description("Product is a member of this product category.")]
    public string ProductCategory { get; set; }

    [Description("Product is a member of this product model.")]
    public string ProductModel { get; set; }

    [Description("Date the product was available for sale.")]
    public DateTime SellStartDate { get; set; }

    [Description("Date the product was no longer available for sale.")]
    public DateTime? SellEndDate { get; set; }

    [Description("Date the product was discontinued.")]
    public DateTime? DiscontinuedDate { get; set; }

    public static ProductDetail from(Product item) {
        return new ProductDetail {
            ProductId = item.ProductId,
            Name = item.Name,
            ProductNumber = item.ProductNumber,
            Color = item.Color,
            StandardCost = item.StandardCost,
            ListPrice = item.ListPrice,
            Size = item.Size,
            Weight = item.Weight,
            ProductCategory = item.ProductCategory?.Name,
            ProductModel = item.ProductModel?.Name,
            SellStartDate = item.SellStartDate,
            SellEndDate = item.SellEndDate,
            DiscontinuedDate = item.DiscontinuedDate
        };
    }

}
