// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace TiendaAW.Entities;

[Table("ProductModel", Schema = "SalesLT")]
[Index("Name", Name = "AK_ProductModel_Name", IsUnique = true)]
[Index("Rowguid", Name = "AK_ProductModel_rowguid", IsUnique = true)]
[Index("CatalogDescription", Name = "PXML_ProductModel_CatalogDescription")]
public partial class ProductModel
{
    [Key]
    [Column("ProductModelID")]
    [JsonPropertyName("id")]
    public int ProductModelId { get; set; }

    [Required]
    [StringLength(50)]
    [JsonPropertyName("modelo")]
    public string Name { get; set; }

    [Column(TypeName = "xml")]
    [JsonPropertyName("descripcion")]
    public string CatalogDescription { get; set; }

    [Column("rowguid")]
    [JsonIgnore]
    public Guid Rowguid { get; set; }

    [Column(TypeName = "datetime")]
    [JsonIgnore]
    public DateTime ModifiedDate { get; set; }

    [InverseProperty("ProductModel")]
    [JsonIgnore]
    public virtual ICollection<ProductModelProductDescription> ProductModelProductDescriptions { get; set; } = new List<ProductModelProductDescription>();

    [InverseProperty("ProductModel")]
    [JsonIgnore]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}