// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace TiendaAW.Entities;

/// <summary>
/// High-level product categorization.
/// </summary>
[Table("ProductCategory", Schema = "SalesLT")]
[Index("Name", Name = "AK_ProductCategory_Name", IsUnique = true)]
[Index("Rowguid", Name = "AK_ProductCategory_rowguid", IsUnique = true)]
public partial class ProductCategory
{
    /// <summary>
    /// Primary key for ProductCategory records.
    /// </summary>
    [Key]
    [Column("ProductCategoryID")]
    [JsonPropertyName("id")]
    public int ProductCategoryId { get; set; }

    /// <summary>
    /// Product category identification number of immediate ancestor category. Foreign key to ProductCategory.ProductCategoryID.
    /// </summary>
    [Column("ParentProductCategoryID")]
    [JsonPropertyName("parentid")]
    public int? ParentProductCategoryId { get; set; }

    /// <summary>
    /// Category description.
    /// </summary>
    [Required]
    [StringLength(50)]
    [JsonPropertyName("category")]
   public string Name { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    [Column("rowguid")]
    [JsonIgnore]
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    [Column(TypeName = "datetime")]
    [JsonIgnore]
    public DateTime ModifiedDate { get; set; }

    [InverseProperty("ParentProductCategory")]
    [JsonIgnore]
    public virtual ICollection<ProductCategory> InverseParentProductCategory { get; set; } = new List<ProductCategory>();

    [ForeignKey("ParentProductCategoryId")]
    [InverseProperty("InverseParentProductCategory")]
    [JsonIgnore]
    public virtual ProductCategory ParentProductCategory { get; set; }

    [InverseProperty("ProductCategory")]
    [JsonIgnore]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}